export enum V1RegisterMethod {
    "REGISTER_METHOD_UNSPECIFIED" = "REGISTER_METHOD_UNSPECIFIED",
    "REGISTER_METHOD_AUTH_KEY" = "REGISTER_METHOD_AUTH_KEY",
    "REGISTER_METHOD_CLI" = "REGISTER_METHOD_CLI",
    "REGISTER_METHOD_OIDC" = "REGISTER_METHOD_OIDC"
}