export const enum V1RegisterMethodEnum {
  'REGISTER_METHOD_UNSPECIFIED' = 'REGISTER_METHOD_UNSPECIFIED',
  'REGISTER_METHOD_AUTH_KEY' = 'REGISTER_METHOD_AUTH_KEY',
  'REGISTER_METHOD_CLI' = 'REGISTER_METHOD_CLI',
  'REGISTER_METHOD_OIDC' = 'REGISTER_METHOD_OIDC',
}

/**
 * @default REGISTER_METHOD_UNSPECIFIED
 */
export type V1RegisterMethod = V1RegisterMethodEnum